#pragma once
#include <limits>
#include <memory>
#include <utility>
#include <thread>
#include <assert.h>
#include <fstream>
#include <iostream>
#include <string>
#include <algorithm>
#include <functional>
#include <numeric>
#include <map>
#include <vector>
#include <random>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <assert.h>
#include <queue>
#include <set>
#include <unordered_set>
#include <bitset>
#include <iomanip>
#include <regex>
#include <exception>
#include <cstring>
#include <ranges>
#include "../DataStructuresAlgorithms/DataStructuresAlgorithms.h"
#include "../DataStructuresAlgorithms/MyStack.h"
#include "../DataStructuresAlgorithms/LongestCommonSubsequence.h"
#include "../DataStructuresAlgorithms/KnapSack.h"
