#pragma once
#include "targetver.h"

#include <stdio.h>
#ifdef _MSC_VER
#include <tchar.h>
#endif

#include <assert.h>
#include <cfloat>
#include <limits>
#include <memory>
#include <utility>
#include <thread>
#include <fstream>
#include <iostream>
#include <string>
#include <algorithm>
#include <functional>
#include <numeric>
#include <map>
#include <unordered_map>
#include <vector>
#include <set>
#include <stack>
#include <queue>
#include <random>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <queue>
#include <set>
#include <unordered_set>
#include <bitset>
#include <iomanip>
#include <regex>
#include <exception>
#include <cstring>
#include <ranges>
#include <variant>
#include <typeinfo>
#include <limits.h>
#include <cmath>
#include <chrono>
#include <concepts>
#include <functional>
#include <generator>
#include <sstream>
#include <stdexcept>
#include <charconv>
#include <cstdint>
#include <cstddef>
#include <math.h>
#include <cfenv>
#include <iterator>
#include "oneapi/tbb.h"
#include "pcg_extras.hpp"
#include "pcg_random.hpp"
#include "pcg_uint128.hpp"
#include "GenericConstraints.h"
using namespace std;
using namespace oneapi::tbb;
